### ISSUE TITLE
AWS Memcached or Redis Type Moodle error

### ISSUE THREAD

**Issue by anmalatesta** [aws-samples/aws-refarch-moodle#41]
Hi, i have installed the template in the AWS Milan region and if i choose Memcached for Session and Application. After to put IsMoodleSetupCompleted  to "Yes" and restart the Pipeline i have a Moodle error because the memcached module is not found.

In the install_cacheclient.sh i found that seems to be an error, the command **tar -xf  tar -xf '/tmp/latest-64bit-X86**  seems has not the **openssl3**  suffix so it is impossible to copy the **amazon-elasticache-cluster-client.so** in  **/usr/lib64/php/modules**/ .

Moreover I have to modify the **/etc/php.d/50-memcached.ini** and the **/etc/php.d/20-redis.ini** file to change the **extension=/usr/lib64/php/modules/amazon-elasticache-cluster-client.so** in **extension=amazon-elasticache-cluster-client** .

After this change I have another issue infact on my AWS AMI the openssl version is **1.0.2k** but seems i need **openssl 3.0**

I tried to change **amazon-elasticache-cluster-client.so** for my openssl version as descibed in https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/Appendix.PHPAutoDiscoverySetup.Installing.html but than i have issues with other components.

Moreover the **extension=igbinary.so** seems to be not present.
Am I doing something wrong ?

Thank you 

Best Regards

Andrea Malatesta

**Comment by dta121** [comment]
Hello, I'm running into the same issue.

**Comment by irshadc** [comment]
Hi Andrea, 

Thanks for pointing out the issue and it seems script is breaking because of suffix 'openssl3' and rest of script is not getting executed. We will release fix for the issue in coming days.

**Comment by albertolarah** [comment]
> 

please, ¿any update?

**Comment by albertolarah** [comment]
> Hi Andrea,
> 
> Thanks for pointing out the issue and it seems script is breaking because of suffix 'openssl3' and rest of script is not getting executed. We will release fix for the issue in coming days.

Please, any update?

**Comment by vrioux** [comment]
This issue has been fixed. Thank you for your patience!

**Comment by albertolarah** [comment]
With the last version I still have the error "Exception - Class "Redis" not found" ¿any update?
